travis:
  secure:
    BINSTAR_TOKEN: snIoQtyL3xLlcPv3AGyfifNcQWVkzgL/QuvGDTRQCOa7NFLdZok4SZ9MzwhzF+iaDpozUiIVl8+6fWcANa1rjTatsjVF+KwY6H+pyzh1PiNXQkFVYqhIsvFgRSR6u8Uhka0pU3yS0CKVPzYi6+irLPjvY/yEjf4BFMQMLNxrUXiAseuiFTLSaYTpKnyDmYxiwmdBNyEBiGljFT3Hej1ihcAwACPY6y46qsWd9eEX58r4h1VdIBryw0i9/La+TKbobLnkkaCyT8KsDqyKw7V44m2xrI9bMsLAWyJQimAq7WjeqcXG6uDHUjMJLdwI8ldXgl4HcXePMl41pF3IasYEqYNQ+dzqcAzUBdb9icmSuVDxrxxortEtkan2GgjGdJyWVUSZwbPmsGv9bS34njdm3KJ8zgjhm1Cy5nyZ7gVpaYxE8UoU8upRtnAkxyorO8ajOD+yJO6plecztaM7bTCZBiaRK75ygdnnCGjjVNJHADzoKLyQx0d62xZYmDadFHTnVFpixzylk9DF9ivNspLtTO5unfXhuHasWeZmfwbKDqZp2DLYhHU7ZYunxbdYAPd1Q+59R7C0cg/2YPS4ZyePwK3Ts2P3TyiNQH+UTyAY7o5DP+BrTOLqyRMPRKuEqg2yQJEwYsWs7X/syJGjZjKHek9+pzBU3GhNB+PzM/h6IEA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
